# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.layers.experimental import preprocessing

In [2]:
tf.__version__

'2.5.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
dataset['Geography'].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [5]:
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [7]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [8]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [32]:
print(X[1])

[0.0 0.0 1.0 608 0 41 1 83807.86 1 0 1 112542.58]


One Hot Encoding the "Geography" column

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
print(X[-2])

[0.0 1.0 0.0 772 1 42 3 75075.31 2 1 0 92888.52]


In [12]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

### Splitting the dataset into the Training set and Test set

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [14]:
X_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

## Part 2 - Building the ANN

### Initializing the ANN

In [15]:
model = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [16]:
model.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

### Adding the second hidden layer

In [17]:
model.add(tf.keras.layers.Dense(units=6, activation = 'relu'))

### Adding the output layer

In [20]:
model.add(tf.keras.layers.Dense(units=1, activation = 'sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [21]:
model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [22]:
model.fit(X_train, y_train, batch_size = 36, epochs = 100)

Epoch 1/100
223/223 [==============================] - 1s 2ms/step - loss: 1.0805 - accuracy: 0.2183
Epoch 2/100
223/223 [==============================] - 0s 1ms/step - loss: 0.6209 - accuracy: 0.7426
Epoch 3/100
223/223 [==============================] - 0s 1ms/step - loss: 0.5483 - accuracy: 0.7960
Epoch 4/100
223/223 [==============================] - 0s 1ms/step - loss: 0.5223 - accuracy: 0.7960
Epoch 5/100
223/223 [==============================] - 0s 1ms/step - loss: 0.5070 - accuracy: 0.7960
Epoch 6/100
223/223 [==============================] - 0s 1ms/step - loss: 0.4915 - accuracy: 0.7960
Epoch 7/100
223/223 [==============================] - 0s 1ms/step - loss: 0.4728 - accuracy: 0.7960
Epoch 8/100
223/223 [==============================] - 0s 1ms/step - loss: 0.4559 - accuracy: 0.7990
Epoch 9/100
223/223 [==============================] - 0s 970us/step - loss: 0.4434 - accuracy: 0.8213
Epoch 10/100
223/223 [==============================] - 0s 1ms/step - loss: 0.4345 - accu

223/223 [==============================] - 0s 1ms/step - loss: 0.3897 - accuracy: 0.8399
Epoch 81/100
223/223 [==============================] - 0s 1ms/step - loss: 0.3894 - accuracy: 0.8415
Epoch 82/100
223/223 [==============================] - 0s 1ms/step - loss: 0.3894 - accuracy: 0.8411
Epoch 83/100
223/223 [==============================] - 0s 1ms/step - loss: 0.3895 - accuracy: 0.8394
Epoch 84/100
223/223 [==============================] - 0s 1ms/step - loss: 0.3894 - accuracy: 0.8407
Epoch 85/100
223/223 [==============================] - 0s 1ms/step - loss: 0.3891 - accuracy: 0.8403
Epoch 86/100
223/223 [==============================] - 0s 1ms/step - loss: 0.3891 - accuracy: 0.8405
Epoch 87/100
223/223 [==============================] - 0s 1ms/step - loss: 0.3890 - accuracy: 0.8411
Epoch 88/100
223/223 [==============================] - 0s 1ms/step - loss: 0.3893 - accuracy: 0.8409
Epoch 89/100
223/223 [==============================] - 0s 1ms/step - loss: 0.3887 - accuracy: 

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [35]:
y_pred = model.predict(X_test)
y_pred[:5]

array([[0.16445732],
       [0.23552218],
       [0.09564131],
       [0.0809246 ],
       [0.12946355]], dtype=float32)

In [29]:
y_predict = []
for i in y_pred:
    if i>0.5:
        y_predict.append(1)
    else:
        y_predict.append(0)

In [30]:
y_predict[:10]

[0, 0, 0, 0, 0, 1, 0, 0, 0, 1]

In [31]:
y_test[:10]

array([0, 1, 0, 0, 0, 1, 0, 0, 1, 1], dtype=int64)

Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

In [33]:
new = model.predict([[1,0,0,600,1,40,3,60000,2,1,1,50000]])

In [34]:
new

array([[0.22224277]], dtype=float32)